How We Use Client-Server Interfaces
Kvalifik/how-we-work pull request #101
Opened 2021-12-07 14:36 UTC by Snailed

Fixes Kvalifik/how-we-work#45-How We Use Result Type Interfaces

2021-12-07 15:11 UTC, nikolajvonholck requested changes

2021-12-07 15:11 UTC, nikolajvonholck commented on how-we-design-client-server-interfaces.md
> +type APISuccess<T> = { ok: T }
It should comply with this file (it currently doesn't :) ): 
https://github.com/Kvalifik/template-backend-nestjs/blob/staging/src/utils/api.ts
structure `{ok: T | true} | {error: string}`

2021-12-07 16:01 UTC, Snailed commented on how-we-design-client-server-interfaces.md
> +type APISuccess<T> = { ok: T }
I'm partial to changing the template type instead, NestJS automatically sends `{ statusCode: number, message: string }` when it throws an error. What do you think?

2021-12-09 09:30 UTC, nikolajvonholck commented on how-we-design-client-server-interfaces.md
> +type APISuccess<T> = { ok: T }
We can do that, but then `{ statusCode: number, message: string }` should be stored as a value for the key `error`.

2021-12-13 16:02 UTC, Snailed commented on how-we-design-client-server-interfaces.md
> +type APISuccess<T> = { ok: T }
Then we will have to change our backends to send the type `{ error: { statusCode: number, message: string }}` instead of `{ statusCode: number, message: string }`. If we choose to do this, we should create a separate issue on the backend template.

2021-12-14 12:39 UTC, nikolajvonholck commented on how-we-design-client-server-interfaces.md
> +type APISuccess<T> = { ok: T }
We already have something along those lines, namely in https://github.com/Kvalifik/template-backend-nestjs/blob/staging/src/utils/result.interceptor.ts

https://github.com/Kvalifik/template-backend-nestjs/blob/staging/src/utils/exception.filter.ts

However, we should consider extending `ErrorResponse` (instead of simply being a string) in https://github.com/Kvalifik/template-backend-nestjs/blob/staging/src/utils/api.ts

What would you recommend? Do we need more than a string as error?

2022-01-03 14:58 UTC, Snailed commented on how-we-design-client-server-interfaces.md
> +type APISuccess<T> = { ok: T }
I can think of multiple scenarios where server-side validation is needed. In this case, an error might need to contain some information on what went wrong. 
This can be an enum or something along those lines. We did do something like that with MitPensum https://github.com/Kvalifik/mitpensum-backend/blob/5b306b0eb203eba83461648e16b6171a95f22632/src/types/response.ts#L39

Maybe the type should be 
~~~typescript
enum APIErrorCode {
  BAD_REQUEST = 0,
  SERVER_ERROR = 1,
  INVALID_PERMISSIONS = 2,
  TOKEN_EXPIRED = 3,
  NOT_FOUND = 4,
  WRONG_EMAIL_PASSWORD_COMBINATION = 5,
  EMAIL_ALREADY_EXISTS = 6,
  ...
}

export type ErrorResponse = {
  error: {
    msg: string,
    code: number
  }
}
~~~

Of course, HTTP codes already provide some of this functionality, but this gives us more extensibility

2022-01-03 14:59 UTC, Snailed commented on how-we-design-client-server-interfaces.md
> +type APISuccess<T> = { ok: T }
It is also crucial that APIErrorCode is isomorphic on both front- and backend

2022-01-07 10:29 UTC, nikolajvonholck commented on how-we-design-client-server-interfaces.md
> +type APISuccess<T> = { ok: T }
I'm not sure we actually need this level of detail (i.e. having more than a simple string as error object) or if it is in fact just added complexity. I think it is the latter as we can handle most errors with HTTP status codes. However, you are right that for some auth related endpoints and endpoints with complex input validation, then it might be nice with a greater level of detail. However, we usually don't display the error message directly in the frontend, so one could use the error string to indicate the different scenarios. After some thought I still prefer the following format:

```
type ResponseResult<R> = { ok: R }
type ResponseError = { error: string }
type Response<R> = ResponseResult<R> | ResponseError
```

2022-05-06 14:29 UTC, Snailed commented
Closed for not complying with our current development practices

2022-05-06 14:29 UTC, closed without merging