Describe how we use serialization in nestJs
Kvalifik/how-we-work pull request #137
Opened 2022-01-27 10:28 UTC by silasbohling

2022-02-01 09:06 UTC, GustavMH requested changes

2022-02-01 09:06 UTC, GustavMH commented on how-we-use-nodejs.md
> +
Maybe add:

#### Example

Consider a nullable string. In the backend it is stored as `String | null`, while the backend will create a query for this value that can fail, so the backend handles `String | null | undefined`. The final step is sending the user the value which is of type `String | undefined`.

```
Database         Backend                      Frontend
String | null -> String | null | Undefined -> String | Undefined
```

2022-02-02 10:04 UTC, silasbohling commented on how-we-use-nodejs.md
> +
If we just use the example from EV Remarketing where a `Submission` entity has an optional value of `offerComment`. Then the property of Submission will be type `String | null`, but when using typeorm's repository api to retrieve a submission from database it will return type `Submission | undefined` and therefore indirectly giving offerComment a type of `String | null | undefined`.

I think that is standard behaviour and easily deducted when looking at different typeorm methods return type. But please advice me if you disagree. 😄

2022-02-02 10:36 UTC, madskchristensen commented on how-we-use-nodejs.md
> +We reccomend to strip objects for null values and return them as undefined instead.
maybe add reason for this recommendation

2022-02-02 10:36 UTC, madskchristensen requested changes
see comment

2022-02-02 10:43 UTC, madskchristensen approved these changes

2022-02-02 10:44 UTC, merged