Add Forecast documentation
Kvalifik/how-we-work pull request #6
Opened 2021-08-13 13:27 UTC by widding

Fixes #4-Add 'How we use Forecast'

2021-11-01 10:17 UTC, Snailed requested changes

2021-11-01 10:17 UTC, Snailed commented on how-we-use-forecast.md
> +When developing, we strive to have 1 Task = 1 Feature = 1 Branch on a project. So if you have a task in Forecast called 'Add Sticky navigation', you should ideally be working on a branch and pull-req
```suggestion
We strive to have each task correspond to one (and only one) feature and git branch.
```

2021-11-01 10:17 UTC, Snailed commented on how-we-use-forecast.md
> +When developing, we strive to have 1 Task = 1 Feature = 1 Branch on a project. So if you have a task in Forecast called 'Add Sticky navigation', you should ideally be working on a branch and pull-req
redundant

2021-11-01 10:17 UTC, Snailed commented on how-we-use-forecast.md
> +To aid this, we use Forecasts GitHub integration and [Kvalifik-CLI](https://github.com/Kvalifik/Kvalifik-CLI) to automatically fetch tasks from Forecast and generate Branches/PRs based on these.
```suggestion
To aid this, we use Forecast's GitHub integration and [Kvalifik-CLI](https://github.com/Kvalifik/Kvalifik-CLI) to automatically fetch tasks from Forecast and generate corresponding branches/PRs.
```

2021-11-01 10:17 UTC, Snailed commented on how-we-use-forecast.md
> +Forecast does not automatically integrate with GitHub, so there's a bit of setup needed.
```suggestion
Forecast does not automatically integrate with GitHub, so there is a bit of setup needed.
```
my English teacher did not like abbreviations in formal texts, but i don't know if we use them here

2021-11-01 10:17 UTC, Snailed commented on how-we-use-forecast.md
> +All Forecast projects that involve code, needs to have a linked GitHub Repository.
```suggestion
All Forecast projects that involve code need to have a linked GitHub repository.
```

2021-11-01 10:17 UTC, Snailed commented on how-we-use-forecast.md
> +The GitHub integration is a 2-way sync of Forecast Task with GitHub Issues. This means that every task in Forecast, exists as an issue on the linked repository. Assignees\*, labels, description, comm
```suggestion
The GitHub integration is a 2-way sync of Forecast tasks with GitHub issues. This means that every task in Forecast exists as an issue on the linked repository. Assignees\*, labels, descriptions, comments and milestones/phases are also synchronised.
```

2021-11-01 10:17 UTC, Snailed commented on how-we-use-forecast.md
> +Please only select 1 repository, even if Forecast let's you select multiple. We _**can't**_ synchronise 1 project with multiple repositories. For Forecast projects that require multiple repositories,
```suggestion
Please only select 1 repository, even if Forecast lets you select multiple. It is currently **impossible** synchronise 1 project with multiple repositories.
```

2021-11-01 10:17 UTC, Snailed commented on how-we-use-forecast.md
> +Like our projects, all Forecast profiles should be integrated with GitHub. This is especially helpful when assigning tasks, as this is synchronised between Forecast & GitHub.
```suggestion
All Forecast profiles should be integrated with GitHub, so task assignments are synchronised correctly between Forecast and GitHub.
```

2021-11-01 10:17 UTC, Snailed commented on how-we-use-forecast.md
> +To link your GitHub account to Forecast, go to ['My Profile'](https://app.forecast.it/my-profile/profile), and scroll down to the bottom. When successfully linked, it should look like this:
```suggestion
To link your GitHub account to Forecast, go to ['My Profile'](https://app.forecast.it/my-profile/profile) and scroll down to the bottom. When successfully linked, it should look like this:
```

2021-11-01 10:17 UTC, Snailed commented on how-we-use-forecast.md
> +Now, everytime you're assigned to a task in Forecast, you'll also be assigned to the Issue in GitHub. This let's you easily filter between issues when working in larger dev teams. Kvalifik-CLI has a
```suggestion
Now, every time you are assigned to a task in Forecast, you will also be assigned to the issue in GitHub. This lets you easily filter between issues when working in larger teams. Kvalifik-CLI has a handy '-a' flag on the 'work-on' command that only shows issues assigned to you: `kvalifik w -a`
```

2021-11-01 10:17 UTC, Snailed commented on how-we-use-forecast.md
> +In practice, the Forecast/Github Integration handles most of the work. Every time a task is added to a project it automatically beocmes an Issue in the linked GitHub repository. If changes are made t
```suggestion
In practice, the Forecast/GitHub Integration handles most of the work. Every time a task is added to a project, it automatically becomes an issue in the linked GitHub repository. The issue will also react accordingly to any changes made to the task.
```

2021-11-01 10:17 UTC, Snailed commented on how-we-use-forecast.md
> +To begin working on a task, clone the repository, write `kvalifik w` in your terminal and select the task from the list. This sets up a branch and draft pull request that's linked to the issue.
```suggestion
To begin working on a task, clone the repository, write `kvalifik w` in your terminal and select the task from the list. This sets up a branch and draft pull request that is linked to the issue.
```

2021-11-01 10:17 UTC, Snailed commented on how-we-use-forecast.md
> +> At this point, you might need to manually move the task in Forecast into 'In Progress' to let your teammates know that you've picked up the task.
```suggestion
> At this point, you might need to manually move the task in Forecast into 'In Progress' to let your teammates know that you have picked up the task.
```

2021-11-01 10:17 UTC, Snailed commented on how-we-use-forecast.md
> +> If your project has a column called 'Ready for Review', 'Code Review', 'Awaiting Approval' or similar, you should move the task into it; so everyone _not_ on GitHub is aware of what's going on.
```suggestion
> If your project has a column called 'Ready for Review', 'Code Review', 'Awaiting Approval' or similar, you should move the task into it; this will make everyone _not_ on GitHub aware of what is going on as well.
```

2021-11-01 10:17 UTC, Snailed commented on how-we-use-forecast.md
> +Once your code has been reviewed, approved hopefully, and merged, the issue is closed and the task in Forecast is moved to the closest 'Done' column.
```suggestion
Once your code has been reviewed (and hopefully approved and merged), the issue is closed and the task in Forecast is moved to the closest 'Done' column.
```
Will this be done automatically?

2021-11-12 12:40 UTC, nikolajvonholck requested changes
Looks good! However, you need to add an entry in the table of contents. Afterwards, you can just merge 💯

2021-11-30 13:25 UTC, merged