Add hard-earned new learnings...
Kvalifik/how-we-work pull request #79
Opened 2021-11-10 14:33 UTC by MariusVB

2021-11-12 12:41 UTC, nikolajvonholck commented on how-we-use-nodejs.md
>  @ManyToMany(() => Entity1, (e: Entity2) => e.entity2s, { eager: true })
Why do we have `eager: true`?

2021-11-12 12:43 UTC, nikolajvonholck requested changes
See my comments.

2021-11-12 12:43 UTC, nikolajvonholck commented on how-we-use-nodejs.md
>  @JoinTable({ name: 'entity1_to_entity2' })
This second `@JoinTable` should be removed.

2021-11-12 12:43 UTC, nikolajvonholck commented on how-we-use-nodejs.md
> +- If you want to access relations lazily by just writing `entity1.entity2`, you need to wrap the attribute type in `Promise`. However this adds a lot of annoyance when working with the relation, like
Could we shorten this to focus on what we do (i.e. `{ relations: ['entity2'] }`) and remove some of what we don't (Promise, eager, etc)?

2021-11-12 12:44 UTC, nikolajvonholck commented on how-we-use-nodejs.md
>  @JoinTable({ name: 'entity1_to_entity2' })
It should only be a decorator on 1 side of the two entities. Consider adding a comment about this :)

2021-11-13 12:09 UTC, MariusVB commented on how-we-use-nodejs.md
> +- If you want to access relations lazily by just writing `entity1.entity2`, you need to wrap the attribute type in `Promise`. However this adds a lot of annoyance when working with the relation, like
We do use eager relations as they just "append" `{ relations: ['entity2'] }` to any `find` command on that entity. I have re-written it and focused on not using lazy relations.

2021-11-13 12:10 UTC, MariusVB commented on how-we-use-nodejs.md
>  @ManyToMany(() => Entity1, (e: Entity2) => e.entity2s, { eager: true })
If we have an entity that should always include a relation, we can specify this. Like an `Attendance` should always have it's `Participant` and `Event` loaded with it.

2021-11-15 09:03 UTC, nikolajvonholck approved these changes
Looks good 👍

2021-11-15 09:18 UTC, merged